name: SGPO
channels:
  - conda-forge
  - defaults
  - bioconda  # added for mafft and mmseqs2 installation
dependencies:
  - python=3.9
  - lightning
  - transformers
  - wandb
  - ipykernel
  - biopython
  - mmseqs2
  - mafft
  - timm
  - botorch
  - pip
  - seaborn
  - torch-scatter # adde for later installation of evodiff
  - pip:
      - hydra-core
      - numpy
      - torch  # handled via conda for GPU compatibility if needed
      - evodiff # added to install together with SGPO core components
      - flash-attn # added to install together with SGPO core components
  